apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-application-devfile-sample-code-with-quarkus-jjjo-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-application-devfile-sample-code-with-quarkus-jjjo-sample
    app.kubernetes.io/part-of: my-application
  name: my-application-devfile-sample-code-with-quarkus-jjjo-sample
  namespace: abhindas-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: my-application-devfile-sample-code-with-quarkus-jjjo-sample
status:
  loadBalancer: {}
